### PR TITLE
SSE: fix retry handling (closes #375)

### LINKED ISSUE #375: SSE reconnect issue
Hi,

`EventSource` is unable to reconnect to the server in the following scenarios.

1. The server is unavailable, the client starts - the client is unable to connect to the server when the server starts up. 
2. The server is available, the client connects to the server. Then the server gets restarted before sending any message to the client - the client is unable to reconnect to the server.

### PR DESCRIPTION
**Pull request by hseeberger**

### CODE REVIEW

File: sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala [hunk 1]
```diff
@@ -103,6 +104,7 @@ object EventSource {
 
     val lastEventId =
       Flow[ServerSentEvent]
+        .prepend(Source.single(heartbeat)) // to make sliding and collect-matching work
```
Comment (hseeberger) [inline sse/src/main/scala/akka/stream/alpakka/sse/scaladsl/EventSource.scala]: This is the only relevant change, the rest is cosmetics.
