### PR TITLE
Empty s3 upload fails

### LINKED ISSUE #806: s3 upload fails on empty source
when trying to upload an empty file, we're getting this exception:
```
The future returned an exception of type: java.lang.RuntimeException, with message: No Responses.
ScalaTestFailureLocation: akka.stream.alpakka.s3.scaladsl.S3SinkSpec at (S3SinkSpec.scala:79)
org.scalatest.exceptions.TestFailedException: The future returned an exception of type: java.lang.RuntimeException, with message: No Responses.
	at org.scalatest.concurrent.Futures$FutureConcept.tryTryAgain$1(Futures.scala:531)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl(Futures.scala:550)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValueImpl$(Futures.scala:479)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValueImpl(ScalaFutures.scala:275)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue(Futures.scala:476)
	at org.scalatest.concurrent.Futures$FutureConcept.futureValue$(Futures.scala:475)
	at org.scalatest.concurrent.ScalaFutures$$anon$1.futureValue(ScalaFutures.scala:275)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.$anonfun$new$4(S3SinkSpec.scala:79)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.withFixture(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.runTest(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.runTests(S3SinkSpec.scala:16)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.org$scalatest$FlatSpecLike$$super$run(S3SinkSpec.scala:16)
	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.org$scalatest$BeforeAndAfterAll$$super$run(S3SinkSpec.scala:16)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at akka.stream.alpakka.s3.scaladsl.S3SinkSpec.run(S3SinkSpec.scala:16)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1340)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:1031)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
Caused by: java.lang.RuntimeException: No Responses
	at akka.stream.alpakka.s3.impl.S3Stream.$anonfun$completionSink$2(S3Stream.scala:327)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I was able to reproduce in a simple test case [here](https://github.com/eyalfa/alpakka/blob/empty-s3-upload-fails/s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala#L67-L80),
as far as I understand s3 supports empty files/objects and this seems to be a library bug, as the library simply fails to produce any request for such cases.

I'm willing to take a stub at this and submit a pull request if the community agrees this is indeed a bug.

cc @jypma (as you seem to be the original author)

### PR DESCRIPTION
**Pull request by eyalfa**
fixes #806 

basic idea,
when uploading to s3, if the input stream is empty append a single empty ByteString to the input. this forces the library to actually send request to s3.

### CODE REVIEW

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala [hunk 1]
```diff
@@ -238,6 +239,41 @@ private[alpakka] final class S3Stream(settings: S3Settings)(implicit system: Act
       .mapConcat(r => Stream.continually(r))
       .zip(Source.fromIterator(() => Iterator.from(1)))
 
+  //todo: this seems like a general purpose 'gadget', is there a better place for this kind of beasts?
+  private def conditionalAppendFl: Flow[ByteString, ByteString, NotUsed.type] =
```
Comment (jypma) [inline s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: doesn't `Source.orElse` do this already?

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala [hunk 2]
```diff
@@ -267,7 +303,7 @@ private[alpakka] final class S3Stream(settings: S3Settings)(implicit system: Act
 
     val headers: S3Headers = S3Headers(sse.fold[Seq[HttpHeader]](Seq.empty) { _.headersFor(UploadPart) })
 
-    SplitAfterSize(chunkSize)(Flow.apply[ByteString])
+    SplitAfterSize(chunkSize)(conditionalAppendFl)
```
Comment (jypma) [inline s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: seeing this makes me think this may just be a bug in [`SplitAfterSize`](https://github.com/eyalfa/alpakka/blob/11eacfccf6d414dbf9c195b7b33150262325c3a8/s3/src/main/scala/akka/stream/alpakka/s3/impl/SplitAfterSize.scala#L38). I don't think it creates a single empty sub-stream when seeing a completely empty source stream. Perhaps `onUpstreamFinish()` should be overridden to emit `NewStream` if nothing else was seen?

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala (hunk 1 above)
Comment (eyalfa) [reply s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: don't know, will check

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala (hunk 2 above)
Comment (eyalfa) [reply s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: not sure, it does make sense that empty input yields empty output, in any case this is use-case specific.

**Comment by eyalfa** [comment]
@ennru , hope this does it.

File: s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala [hunk 3]
```diff
@@ -41,7 +55,7 @@ class S3SinkSpec extends S3WireMockBase with S3ClientIntegrationSpec {
 
   it should "upload a stream of bytes to S3 with custom headers" in {
 
-    mockUpload()
+    //mockUpload()
```
Comment (ennru) [inline s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala]: And this is obsolete?

Comment (eyalfa) [reply s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3SinkSpec.scala]: hmm... probably a left over for me trying to figure out why my tests didn't succeed initially... will revert

**Comment by eyalfa** [comment]
@ennru , I think it's sorted out now

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala [hunk 4]
```diff
@@ -16,11 +16,12 @@ import akka.http.scaladsl.model.StatusCodes.{NoContent, NotFound, OK}
...
 import akka.http.scaladsl.model.headers.ByteRange
 import akka.http.scaladsl.unmarshalling.{Unmarshal, Unmarshaller}
-import akka.stream.Materializer
+import akka.stream.{FlowShape, Materializer}
 import akka.stream.alpakka.s3.auth.{CredentialScope, Signer, SigningKey}
 import akka.stream.alpakka.s3.scaladsl.{ListBucketResultContents, ObjectMetadata}
 import akka.stream.alpakka.s3.{DiskBufferType, MemoryBufferType, S3Exception, S3Settings}
-import akka.stream.scaladsl.{Flow, Keep, Sink, Source}
+import akka.stream.scaladsl.{Broadcast, Concat, Flow, GraphDSL, Keep, Sink, Source}
+import GraphDSL.Implicits._
```
Comment (jypma) [inline s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: is this import used?

File: s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala [hunk 5]
```diff
@@ -238,6 +239,8 @@ private[alpakka] final class S3Stream(settings: S3Settings)(implicit system: Act
       .mapConcat(r => Stream.continually(r))
       .zip(Source.fromIterator(() => Iterator.from(1)))
 
+  val conditionalAppendFl = Flow[ByteString].orElse(Source.single(ByteString.empty))
```
Comment (jypma) [inline s3/src/main/scala/akka/stream/alpakka/s3/impl/S3Stream.scala]: the `Fl` suffix stands a bit out of place. Perhaps call it `atLeastOneByteString`? Then the expression below becomes `SplitAfterSize(chunkSize)(atLeastOneByteString)` which reads nicely.

**Comment by ennru** [comment]
Thank you for your contribution. Keep them coming!
