### PR TITLE
Amqp: assert all stages stopped and fix source shutdown

### LINKED ISSUE #1500: AMQP: source doesn't shut down
`AmqpSource`s should shut down properly when downstream is finished, depending on the `NamedQueueSourceSettings.ackRequired` setting.

### Expected Behavior

If `NamedQueueSourceSettings.ackRequired` is false, the AMQP source stage should shut down immediately on downstream finish.

### Actual Behavior

The `NamedQueueSourceSettings.ackRequired` setting enables AMQP's `autoAck` if false, but the source stage is still awaiting acks or nacks for all messages (by counting outstanding acks) before it shuts down.

### PR DESCRIPTION
**Pull request by ennru**
## Fixes

Fixes #1500 

Part of #1223 

## Purpose

Make use of `assertAllStagesStopped` to ensure proper stream shutdown in test cases.
Add `ApiMayChange` on stream element classes as they have unfortunate names.

### CODE REVIEW

File: amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala [hunk 1]
```diff
@@ -156,10 +160,12 @@ private[amqp] final class AmqpSourceStage(settings: AmqpSourceSettings, bufferSi
               pushMessage(queue.dequeue())
             }
 
-          override def onDownstreamFinish(): Unit = {
-            setKeepGoing(true)
-            if (unackedMessages == 0) super.onDownstreamFinish()
-          }
+          override def onDownstreamFinish(): Unit =
+            if (finishWithOutstandingAcks || unackedMessages == 0) super.onDownstreamFinish()
```
Comment (juanjoDiaz) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: I think that it's misleading to have a `unackedMessages` counter different to zero if messages are actually acknowledged.

It would be cleaner to do the check at line 168/174
(https://github.com/akka/alpakka/pull/1501/files#diff-79b48cb12e370d65fef5180dc16ab6aaR174)
like
```scala
      def pushMessage(message: CommittableIncomingMessage): Unit = {
        push(out, message)
        if (super.settings.ackRequired) unackedMessages += 1
      }
```

Comment (ennru) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: You are right. 
Does it have any effect in case `ack` or `nack` are called when `autoAck` is `true`? 
Those could be short-circuited I guess. Or the source should not even emit committable messages...

Comment (juanjoDiaz) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: True.
Probably you should do the same at when the counter is decreased: `if (super.settings.ackRequired) unackedMessages -= 1` or even ``if (unackedMessages > 0) unackedMessages -= 1` to ensure that it doesn't go negative.

Comment (ennru) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: I went a bit further and made ack/nack no-ops when using auto-ack.

Comment (juanjoDiaz) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: Looks great now.

However, I still think that the API is kind of broken (as discussed in #1167 ) since you can use the `withAckRequired` when creating a `committableSource` which doesn't make sense.

Comment (ennru) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: Yes, you're right. I'll put an API might change there.

Comment (ennru) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: I've created #1513

Comment (juanjoDiaz) [reply amqp/src/main/scala/akka/stream/alpakka/amqp/impl/AmqpSourceStage.scala]: Thanks!

Apart from that, the PR LGTM!
It fixes the actual issue and doesn't touch the current API.
