### PR TITLE
Fix timing issue in Elasticsearch tests

### LINKED ISSUE #479: ElasticsearchTest
```
----------------------------------------
Cluster Name: elasticsearch-cluster-runner
Base Path:    /tmp/es-cluster431932489297553471
----------------------------------------
Cluster Name: elasticsearch-cluster-runner
Base Path:    /tmp/es-cluster4836132851537540940
Num Of Node:  1
----------------------------------------
Num Of Node:  1
----------------------------------------
Creating /tmp/es-cluster431932489297553471/config/node_1
Creating /tmp/es-cluster4836132851537540940/config/node_1
Creating /tmp/es-cluster431932489297553471/logs/node_1
Creating /tmp/es-cluster431932489297553471/data/node_1
Creating /tmp/es-cluster4836132851537540940/logs/node_1
Creating /tmp/es-cluster4836132851537540940/data/node_1
Node Name:      Node 1
HTTP Port:      9211
Transport Port: 9311
Data Directory: /tmp/es-cluster4836132851537540940/data/node_1
Log Directory:  /tmp/es-cluster4836132851537540940/logs/node_1
----------------------------------------
Node Name:      Node 1
HTTP Port:      9201
Transport Port: 9301
Data Directory: /tmp/es-cluster431932489297553471/data/node_1
Log Directory:  /tmp/es-cluster431932489297553471/logs/node_1
----------------------------------------
Creating /tmp/es-cluster431932489297553471/modules
Creating /tmp/es-cluster431932489297553471/plugins
Creating /tmp/es-cluster4836132851537540940/modules
Creating /tmp/es-cluster4836132851537540940/plugins
[2017-09-19T11:38:00,030][INFO ][o.e.n.Node               ] [Node 1] initializing ...
[2017-09-19T11:38:00,029][INFO ][o.e.n.Node               ] [Node 1] initializing ...
[2017-09-19T11:38:00,174][INFO ][o.e.e.NodeEnvironment    ] [Node 1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [16gb], net total_space [29.4gb], spins? [no], types [ext4]
[2017-09-19T11:38:00,179][INFO ][o.e.e.NodeEnvironment    ] [Node 1] using [1] data paths, mounts [[/ (/dev/sda1)]], net usable_space [16gb], net total_space [29.4gb], spins? [no], types [ext4]
[2017-09-19T11:38:00,189][INFO ][o.e.e.NodeEnvironment    ] [Node 1] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-09-19T11:38:00,192][INFO ][o.e.n.Node               ] [Node 1] node name [Node 1], node ID [0uo6S3NHSzihlcDfJqJ_-g]
[2017-09-19T11:38:00,194][INFO ][o.e.n.Node               ] [Node 1] version[5.6.0], pid[7311], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.4.0-93-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-09-19T11:38:00,198][INFO ][o.e.n.Node               ] [Node 1] JVM arguments [-Dfile.encoding=UTF8, -Xms1g, -Xmx1g, -Xss6M, -XX:+CMSClassUnloadingEnabled, -XX:+UseConcMarkSweepGC, -XX:ReservedCodeCacheSize=128m]
[2017-09-19T11:38:00,203][INFO ][o.e.e.NodeEnvironment    ] [Node 1] heap size [1007.3mb], compressed ordinary object pointers [true]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] node name [Node 1], node ID [8SwMlrshQgqYibIM7hsSVw]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] version[5.6.0], pid[7311], build[781a835/2017-09-07T03:09:58.087Z], OS[Linux/4.4.0-93-generic/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_144/25.144-b01]
[2017-09-19T11:38:00,207][INFO ][o.e.n.Node               ] [Node 1] JVM arguments [-Dfile.encoding=UTF8, -Xms1g, -Xmx1g, -Xss6M, -XX:+CMSClassUnloadingEnabled, -XX:+UseConcMarkSweepGC, -XX:ReservedCodeCacheSize=128m]
[2017-09-19T11:38:00,231][INFO ][o.e.p.PluginsService     ] [Node 1] no modules loaded
[2017-09-19T11:38:00,232][INFO ][o.e.p.PluginsService     ] [Node 1] no modules loaded
[2017-09-19T11:38:00,235][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2017-09-19T11:38:00,237][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.ingest.common.IngestCommonPlugin]
[2017-09-19T11:38:00,239][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.painless.PainlessPlugin]
[2017-09-19T11:38:00,241][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[2017-09-19T11:38:00,244][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.expression.ExpressionPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.groovy.GroovyPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[2017-09-19T11:38:00,247][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
[2017-09-19T11:38:00,248][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
[2017-09-19T11:38:00,248][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.ingest.common.IngestCommonPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.painless.PainlessPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
[2017-09-19T11:38:00,249][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.expression.ExpressionPlugin]
[2017-09-19T11:38:00,254][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.groovy.GroovyPlugin]
[2017-09-19T11:38:00,255][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.script.mustache.MustachePlugin]
[2017-09-19T11:38:00,255][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.search.aggregations.matrix.MatrixAggregationPlugin]
[2017-09-19T11:38:00,257][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty3Plugin]
[2017-09-19T11:38:00,257][INFO ][o.e.p.PluginsService     ] [Node 1] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
Closed all nodes.
Deleted /tmp/es-cluster4836132851537540940
[info] Test run started
[error] Test akka.stream.alpakka.elasticsearch.ElasticsearchTest failed: org.codelibs.elasticsearch.runner.ClusterRunnerException: Failed to start node 1, took 0.0 sec
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:360)
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:284)
[error]     at akka.stream.alpakka.elasticsearch.ElasticsearchTest.setup(ElasticsearchTest.java:43)
[error]     ...
[error] Caused by: java.lang.IllegalStateException: availableProcessors is already set to [2], rejecting [2]
[error]     at io.netty.util.NettyRuntime$AvailableProcessorsHolder.setAvailableProcessors(NettyRuntime.java:51)
[error]     at io.netty.util.NettyRuntime.setAvailableProcessors(NettyRuntime.java:87)
[error]     at org.elasticsearch.transport.netty4.Netty4Utils.setAvailableProcessors(Netty4Utils.java:82)
[error]     at org.elasticsearch.transport.netty4.Netty4Transport.<init>(Netty4Transport.java:138)
[error]     at org.elasticsearch.transport.Netty4Plugin.lambda$getTransports$0(Netty4Plugin.java:93)
[error]     at org.elasticsearch.node.Node.<init>(Node.java:430)
[error]     at org.codelibs.elasticsearch.runner.node.ClusterRunnerNode.<init>(ClusterRunnerNode.java:17)
[error]     at org.codelibs.elasticsearch.runner.node.ClusterRunnerNode.<init>(ClusterRunnerNode.java:23)
[error]     at org.codelibs.elasticsearch.runner.ElasticsearchClusterRunner.build(ElasticsearchClusterRunner.java:355)
[error]     ... 50 more
[error] Test akka.stream.alpakka.elasticsearch.ElasticsearchTest failed: java.lang.NullPointerException: null, took 0.0 sec
[error]     at akka.stream.alpakka.elasticsearch.ElasticsearchTest.teardown(ElasticsearchTest.java:70)
[error]     ...
```

### PR DESCRIPTION
**Pull request by takezoe**
Disables parallel test because [elasticsearch-cluster-runner](https://github.com/codelibs/elasticsearch-cluster-runner) which is used to run Elasticsearch for test doesn't support parallel execution on same JVM formally.

Fixes #479.

### CODE REVIEW

File: elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java [hunk 1]
```diff
@@ -39,8 +39,12 @@
 
   @BeforeClass
   public static void setup() throws IOException {
+    System.setProperty("es.set.netty.runtime.available.processors", "false");
```
Comment (raboof) [inline elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java]: Could this obscure actual problems?

Comment (takezoe) [reply elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java]: Sorry, I'm still investigating and testing at my repository. Since this pull request is work in progress, I updated the subject.

For now, we (I and author of elasticsearch-cluster-runner library) think that actual problem is elasticsearch-cluster-runner can't run multiple cluster on same JVM at same time by internal structure of Elasticsearch. Maybe it can be resolved by merge Java test and Scala test.

**Comment by takezoe** [comment]
@raboof This pull request disables parallel execution in elasticsearch project because elasticsearch-cluster-runner doesn't support parallel execution on same JVM formally. It might not be the best solution, but we couldn't find better one.

File: build.sbt [hunk 2]
```diff
@@ -93,6 +93,7 @@ lazy val elasticsearch = project
   .enablePlugins(AutomateHeaderPlugin)
   .settings(
     name := "akka-stream-alpakka-elasticsearch",
+    parallelExecution in ThisBuild := false,
```
Comment (raboof) [inline build.sbt]: Maybe add a comment explaining why this was needed?

File: elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java [hunk 3]
```diff
@@ -40,11 +40,14 @@
...
-    runner.build(ElasticsearchClusterRunner.newConfigs().baseHttpPort(9210).baseTransportPort(9310).numOfNode(1));
+    runner.build(ElasticsearchClusterRunner.newConfigs()
+        .baseHttpPort(9200)
+        .baseTransportPort(9300)
+        .numOfNode(1));
     runner.ensureYellow();
 
     //#init-client
-    client = RestClient.builder(new HttpHost("localhost", 9211)).build();
+    client = RestClient.builder(new HttpHost("localhost", 9201)).build();
```
Comment (raboof) [inline elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java]: When (intentionally) re-using the same port, you could consider putting the actual port number in a constant somewhere and referring to it from both places where you use it.

File: build.sbt (hunk 2 above)
Comment (takezoe) [reply build.sbt]: Thanks, I fixed to disable only test execution and added comment.

File: elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java (hunk 3 above)
Comment (takezoe) [reply elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java]: I think sharing the port number is not necessary. These tests are independent and they don't have to use same port necessarily. It's just no longer necessary to use different ports.

**Comment by takezoe** [comment]
@raboof Fixed.

File: elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java (hunk 3 above)
Comment (raboof) [reply elasticsearch/src/test/java/akka/stream/alpakka/elasticsearch/ElasticsearchTest.java]: Agreed, using a constant make it more obvious that it's intentional though. But OK like this :+1:

**Comment by raboof** [comment]
Thanks!
