### PR TITLE
Specify request JSON encoding explicitly in Elasticsearch connector

### LINKED ISSUE #547: Elasticsearch connector - encoding bug
Hi,

Elasticsearch connector 0.14 fails to post json to elastic if json contains special characters.

Elastic is unable to parse the json and is reporting *Invalid UTF-8 middle byte 0x20*

The problem is located on this line:
https://github.com/akka/alpakka/blob/master/elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala#L135

By changing it from:

     new StringEntity(json)

to

     new StringEntity(json, "utf-8")

the problem is fixed

### PR DESCRIPTION
**Pull request by takezoe**
Fixes #547

### CODE REVIEW

File: elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala [hunk 1]
```diff
@@ -132,7 +132,7 @@ class ElasticsearchFlowStage[T, R](
           "POST",
           "/_bulk",
           Map[String, String]().asJava,
-          new StringEntity(json),
+          new StringEntity(json, "UTF-8"),
```
Comment (johanandren) [inline elasticsearch/src/main/scala/akka/stream/alpakka/elasticsearch/ElasticsearchFlowStage.scala]: Use `StandardCharsets.UTF_8` instead.

**Comment by takezoe** [comment]
@johanandren Thanks for your review. I fixed to use `StandardCharsets.UTF_8` instead of a string literal.
