### PR TITLE
FTP: Improve type safety wrt settings (closes #116)

### LINKED ISSUE #116: FTP connector: improve type safety regarding configuration settings
Currently, it's possible to build `Source` instances from wrong setting types. For instance, you could build a `Source` for `FTP` from `SftpSettings`. The error would be thrown in runtime instead of in compilation time.

### PR DESCRIPTION
**Pull request by juanjovazquez**
See #116

### CODE REVIEW

File: ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala [hunk 1]
```diff
@@ -13,66 +13,66 @@ import java.nio.file.Path
...
 private[ftp] trait FtpSourceFactory[FtpClient] { self =>
 
+  type S <: RemoteFileSettings
+
   protected[this] final val DefaultChunkSize = 8192
 
   protected[this] def ftpClient: FtpClient
 
-  protected[this] def ftpBrowserSourceName: String
+  protected[this] val ftpBrowserSourceName: String
```
Comment (juanjovazquez) [inline ftp/src/main/scala/akka/stream/alpakka/ftp/impl/FtpSourceFactory.scala]: No particular reason. You're right. Changed.
