### PR TITLE
make some gcs object metadata fields optional

### LINKED ISSUE #2163: 2.0.0-M3 GCS Object is missing required member 'retentionExpirationTime'
Alpakka `2.0.0-M3` gcs storage `listBucket` is broken

this was introduced by #2058 ade65897c549f4e0c977bec8fa4b018b34e9bfc2

will create a pr to fix this, are there no real integrations tests on ci?

```
[error]   ! allow moving an object
[error]    spray.json.DeserializationException: Object is missing required member 'retentionExpirationTime' (package.scala:23)
[error] spray.json.package$.deserializationError(package.scala:23)
[error] spray.json.ProductFormats.fromField(ProductFormats.scala:63)
[error] spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$.fromField(Formats.scala:18)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:109)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:95)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:162)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:160)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityTo$1(GCStorageStream.scala:456)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityTo(GCStorageStream.scala:456)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityOptionTo$1(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityOptionTo(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$listBucket$5(GCStorageStream.scala:122)
[error] akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
[error] spray.json.ProductFormats.fromField(ProductFormats.scala:58)
[error] spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$.fromField(Formats.scala:18)
[error] spray.json.ProductFormatsInstances$$anon$18.read(ProductFormatsInstances.scala:677)
[error] spray.json.ProductFormatsInstances$$anon$18.read(ProductFormatsInstances.scala:641)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$StorageObjectJsonFormat$.read(Formats.scala:96)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$StorageObjectJsonFormat$.read(Formats.scala:94)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] spray.json.CollectionFormats$$anon$1.$anonfun$read$1(CollectionFormats.scala:30)
[error] spray.json.CollectionFormats$$anon$1.read(CollectionFormats.scala:30)
[error] spray.json.CollectionFormats$$anon$1.read(CollectionFormats.scala:27)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] spray.json.StandardFormats$OptionFormat.read(StandardFormats.scala:39)
[error] spray.json.StandardFormats$OptionFormat.read(StandardFormats.scala:32)
[error] spray.json.ProductFormats.fromField(ProductFormats.scala:58)
[error] spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$.fromField(Formats.scala:18)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:109)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:95)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:162)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:160)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityTo$1(GCStorageStream.scala:456)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityTo(GCStorageStream.scala:456)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityOptionTo$1(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityOptionTo(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$listBucket$5(GCStorageStream.scala:122)
[error] akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
[error] CAUSED BY
[error]  java.util.NoSuchElementException: key not found: retentionExpirationTime (ProductFormats.scala:58)
[error] spray.json.ProductFormats.fromField(ProductFormats.scala:58)
[error] spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$.fromField(Formats.scala:18)
[error] spray.json.ProductFormatsInstances$$anon$18.read(ProductFormatsInstances.scala:677)
[error] spray.json.ProductFormatsInstances$$anon$18.read(ProductFormatsInstances.scala:641)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$StorageObjectJsonFormat$.read(Formats.scala:96)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$StorageObjectJsonFormat$.read(Formats.scala:94)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] spray.json.CollectionFormats$$anon$1.$anonfun$read$1(CollectionFormats.scala:30)
[error] spray.json.CollectionFormats$$anon$1.read(CollectionFormats.scala:30)
[error] spray.json.CollectionFormats$$anon$1.read(CollectionFormats.scala:27)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] spray.json.StandardFormats$OptionFormat.read(StandardFormats.scala:39)
[error] spray.json.StandardFormats$OptionFormat.read(StandardFormats.scala:32)
[error] spray.json.ProductFormats.fromField(ProductFormats.scala:58)
[error] spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$.fromField(Formats.scala:18)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:109)
[error] spray.json.ProductFormatsInstances$$anon$4.read(ProductFormatsInstances.scala:95)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:162)
[error] akka.stream.alpakka.googlecloud.storage.impl.Formats$BucketListResultReads$.read(Formats.scala:160)
[error] spray.json.JsValue.convertTo(JsValue.scala:33)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityTo$1(GCStorageStream.scala:456)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.transform(FastFuture.scala:84)
[error] akka.http.scaladsl.util.FastFuture$FulfilledFuture.map(FastFuture.scala:77)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityTo(GCStorageStream.scala:456)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$responseEntityOptionTo$1(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.responseEntityOptionTo(GCStorageStream.scala:450)
[error] akka.stream.alpakka.googlecloud.storage.impl.GCStorageStream$.$anonfun$listBucket$5(GCStorageStream.scala:122)
[error] akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
[error] akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
[error] akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
[error] akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
```

### PR DESCRIPTION
**Pull request by francisdb**
Fixes  #2163

Please merge #2164 first

### CODE REVIEW

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala [hunk 1]
```diff
@@ -380,15 +380,15 @@ object StorageObject {
       timeCreated: OffsetDateTime,
       timeDeleted: Option[OffsetDateTime],
       storageClass: String,
-      contentDisposition: String,
-      contentEncoding: String,
-      contentLanguage: String,
+      contentDisposition: Option[String],
```
Comment (francisdb) [inline google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: Should this not be Optional or just String and accept null?

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala [hunk 2]
```diff
@@ -104,15 +104,15 @@ final class StorageObject private (
   def withTimeCreated(value: OffsetDateTime): StorageObject = copy(timeCreated = value)
   def withTimeDeleted(value: OffsetDateTime): StorageObject = copy(timeDeleted = Some(value))
   def withStorageClass(value: String): StorageObject = copy(storageClass = value)
-  def withContentDisposition(value: String): StorageObject = copy(contentDisposition = value)
-  def withContentEncoding(value: String): StorageObject = copy(contentEncoding = value)
-  def withContentLanguage(value: String): StorageObject = copy(contentLanguage = value)
+  def withContentDisposition(value: String): StorageObject = copy(contentDisposition = Some(value))
```
Comment (francisdb) [inline google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: Should this not be Option(_) instead of (Some) to accept null?

Comment (francisdb) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: @ennru do you have some guidance here on what I should do for the java api?

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala (hunk 1 above)
Comment (francisdb) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: @ennru do you have some guidance here on what I should do for the java api?

**Comment by francisdb** [comment]
@seglo maybe you can answer these two questions so I can finish this PR?

File: google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes [hunk 3]
```diff
@@ -0,0 +1,11 @@
+# Make some fields optional https://github.com/akka/alpakka/issues/2163
```
Comment (seglo) [inline google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes]: Rename the file to `2.0.0-M3.backwards.excludes`

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala [hunk 4]
```diff
@@ -55,14 +54,27 @@ private[googlecloud] class GoogleTokenApi(http: => HttpExt) {
         http,
         HttpRequest(HttpMethods.POST, googleTokenUrl, entity = requestEntity)
       )
-      result <- Unmarshal(response.entity).to[OAuthResponse]
+      result <- readResponse(response)
```
Comment (seglo) [inline google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala]: I merged #2164. Please rebase.

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala (hunk 2 above)
Comment (seglo) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: Good point.  Please update any optional reference types to use `Option.apply`.

Comment (seglo) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: Let's keep the optional case class fields as scala `Option` so the spray serdes works correctly.  Please add Java getters that return `Optional` fields (i.e. see `getContentType`).  Here's a simple one liner to wrap an `Option`: `Optional.ofNullable(option.orNull)`.

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala (hunk 1 above)
Comment (seglo) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: If this is indeed an optional parameter then use `Option`.

Comment (seglo) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: See earlier comment about adding a Java API.

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala [hunk 5]
```diff
@@ -118,6 +118,7 @@ import scala.util.control.NonFatal
               .withQuery(Query(queryParams))
         )
       ).runWith(Sink.head)
+        .map(response => response.withEntity(response.entity.withoutSizeLimit))
```
Comment (seglo) [inline google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala]: :+1:

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala (hunk 1 above)
Comment (francisdb) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: @seglo  This method is marked as java api, I would expect nullable values here or Optional

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala (hunk 4 above)
Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala]: done

File: google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes (hunk 3 above)
Comment (francisdb) [reply google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes]: 2.0.0-M3 is already in maven central so this is for 2.0.0-M4?

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala (hunk 2 above)
Comment (francisdb) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: that line does not work with pimitives, used scala.compat.java8.OptionConverters

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala (hunk 5 above)
Comment (francisdb) [reply google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GCStorageStream.scala]: yes, saw that when listing a large bucket

File: google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes (hunk 3 above)
Comment (seglo) [reply google-cloud-storage/src/main/mima-filters/2.0.0-M4.backwards.excludes]: Yes.  It still works with some future version, but it's more correct to use the last published version.  "This is the version I'm making breaking changes from".

**Comment by seglo** [comment]
I'll review this again tomorrow if you're ready.  LMK.

**Comment by francisdb** [comment]
@seglo I am ready

File: google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala [hunk 6]
```diff
@@ -81,6 +84,20 @@ final class StorageObject private (
 
   /** Java API */
   def getContentType: akka.http.javadsl.model.ContentType = contentType.asInstanceOf[ContentType]
+  def getTimeDeleted: Optional[OffsetDateTime] = timeDeleted.asJava
```
Comment (seglo) [inline google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/StorageObject.scala]: I forgot about the `Option` converter :+1:

**Comment by francisdb** [comment]
> LGTM. Thanks a lot @francisdb!
> 
> I'll look into releasing an M4, but it may have to wait until Monday or Tuesday. Hopefully that's alright.

@seglo sure, looking forward to a release that will fix all our 50x GCS errors :-)

**Comment by seglo** [comment]
Hi @francisdb. We have a few more things we'd like to get into Alpakka before doing another milestone release. If you just want an external dependency to reference I suggest using our individual snapshots available on the akka repo.  We publish these every time master builds successfully.  They're not overwritten, but they do get cleaned out infrequently.  It should be able to work for you until another milestone is released.

Here's a version that should include your work.

https://bintray.com/akka/snapshots/alpakka/2.0.0-M3%2B4-3bc12878

Some more info about using the akka repo for snapshots.

https://doc.akka.io/docs/alpakka/2.0/other-docs/snapshots.html

**Comment by francisdb** [comment]
@seglo thanks for pinging me on this, didn't know about these

**Comment by francisdb** [comment]
Looks like I found another issue related to this, expect another pr

**Comment by francisdb** [comment]
@seglo see #2176

**Comment by francisdb** [comment]
@seglo how is that M4 coming along? M3 gcs is totally broken

**Comment by seglo** [comment]
@francisdb We plan to release a 2.0.0 RC next week.

**Comment by francisdb** [comment]
great, thanks, gcs is behaving much better with the snapshot, we have yest to see any persistent 50x errors
