### PR TITLE
fix #374 correctly encodes non-ascii characters for signing s3 requests

### LINKED ISSUE #374: S3 signature doesn't match expected when path contains special chars
Hi guys.

Currently I'm facing an issue with alpakka s3 client 0.10 when accessing a file like `files/überall.csv`
```
The request signature we calculated does not match the signature you provided. Check your key and signing method.
```
When I pass the key with encoded special chars, e.g. `files/%C3%BCberall.csv` I get another exception: `The specified key does not exist.`

Supposedly the issue is related to https://github.com/akka/alpakka/issues/357 and https://github.com/akka/alpakka/issues/316 because in version 0.9 I had exactly the error
`akka.http.scaladsl.model.IllegalUriException: Illegal URI reference: Invalid input 'ü', expected '/', 'EOI', '#', '?' or pchar` for exactly same configuration.

### PR DESCRIPTION
**Pull request by francisdb**
fix #374 correctly encodes non-ascii characters for signing s3 requests

### CODE REVIEW

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala [hunk 1]
```diff
@@ -59,7 +59,13 @@ private[alpakka] object CanonicalRequest {
       pathEncodeRec(builder ++= uriEncodePath(head), tail)
   }
 
-  private def toHexUtf8(ch: Char): String = "%" + Integer.toHexString(ch.toInt)
+  private def toHexUtf8(ch: Char): String = ch match {
+    case asciiChar if ch >= 0 && ch <= 127 =>
+      "%" + Integer.toHexString(asciiChar.toInt).toUpperCase
+    case otherChar =>
+      // I guess this adds quite some overhead but the detailed api is not public
+      Path(otherChar.toString).toString()
```
Comment (francisdb) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: Personally not too fond of this part but I want to avoid re-inventing the wheel on uri encoding

**Comment by francisdb** [comment]
🙄 No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala (hunk 1 above)
Comment (francisdb) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: might take the time to use create a modified version of the akka-http uri encoder that users paraboiled

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala [hunk 2]
```diff
@@ -59,7 +59,13 @@ private[alpakka] object CanonicalRequest {
       pathEncodeRec(builder ++= uriEncodePath(head), tail)
   }
 
-  private def toHexUtf8(ch: Char): String = "%" + Integer.toHexString(ch.toInt)
+  private def toHexUtf8(ch: Char): String = ch match {
```
Comment (gipeshka) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: maybe it makes sense to put this directly into list of cases at line 80

Comment (francisdb) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: well wanted to keep the code close to the aws example

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala (hunk 1 above)
Comment (raboof) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: I suppose it would be neat to expose a `UriRendering.renderPath` that accepts a `keep: CharPredicate` instead of a `encodeFirstSegmentColons: Boolean`, that would make this a lot easier right?

I guess another approach might be to reuse the Path rendering and treat the `sub-delims` characters specially, like this:
```
private def pathEncode(path: Path): String =
    if (path.isEmpty) "/"
    else
      path.toString().flatMap {
        case ch if "!$&'()*+,;=".contains(ch) => "%" + Integer.toHexString(ch.toInt).toUpperCase
        case other => other.toString
      }
```

Comment (francisdb) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: let me do some tests but that indeed seems like a simpler solution 👍

Comment (francisdb) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: Feel free to submit your own pull request if you mind me copy pasting the above code :-)

**Comment by francisdb** [comment]
Should I smash or do you guys handle that on merge?

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala (hunk 1 above)
Comment (raboof) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: Haha no go ahead :)

**Comment by raboof** [comment]
We'll squash & merge

**Comment by francisdb** [comment]
@raboof are we still waiting for something?

File: s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala [hunk 3]
```diff
@@ -47,30 +47,12 @@ private[alpakka] object CanonicalRequest {
   def signedHeadersString(headers: Seq[HttpHeader]): String =
     headers.map(_.lowercaseName()).distinct.sorted.mkString(";")
 
-  private def pathEncode(path: Path): String = path match {
-    case p if p.isEmpty => "/"
-    case nonEmptyPath => pathEncodeRec(new StringBuilder, nonEmptyPath).toString()
-  }
-
-  @tailrec private def pathEncodeRec(builder: StringBuilder, path: Path): StringBuilder = path match {
```
Comment (raboof) [inline s3/src/main/scala/akka/stream/alpakka/s3/auth/CanonicalRequest.scala]: `scala.annotation.tailrec` is now an unused import above

File: s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala [hunk 4]
```diff
@@ -11,17 +11,22 @@ import akka.stream.scaladsl.{Sink, Source}
...
 import com.typesafe.config.ConfigFactory
 import org.scalatest.concurrent.ScalaFutures
-import org.scalatest.{BeforeAndAfterAll, FlatSpecLike, Matchers}
+import org.scalatest.time.{Millis, Seconds, Span}
+import org.scalatest.{BeforeAndAfterAll, FlatSpecLike, Ignore, Matchers}
 
 import scala.concurrent.Await
 import scala.concurrent.duration._
 
+@Ignore
```
Comment (raboof) [inline s3/src/test/scala/akka/stream/alpakka/s3/scaladsl/S3NoMock.scala]: :+1: perhaps add a comment on how to use/enable/run these tests?
