### PR TITLE
Google Storage & Pub-Sub: Retry google token requests on 5xx

### LINKED ISSUE #2080: GCS - Object is missing required member 'access_token'
Alpakka `2.0.0-M2`

We sporadically see this error in our logs, the auth token handling is not handling error responses correctly. In this case a retry should be done like in #2057 and #1931

https://github.com/akka/alpakka/blob/f420069bad2105e86f0c4b69e5221cde7fbeb7fe/google-cloud-storage/src/main/scala/akka/stream/alpakka/googlecloud/storage/impl/GoogleTokenApi.scala#L53-L54

Also apply to the `google-cloud-pub-sub` module

https://github.com/akka/alpakka/blob/f420069bad2105e86f0c4b69e5221cde7fbeb7fe/google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala#L54-L55

Also the trace for this error does not show it is related to alpakka?

```
play.api.UnexpectedException: Unexpected exception[DeserializationException: Object is missing required member 'access_token']
    at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:328)
    at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:251)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:421)
    at play.core.server.AkkaHttpServer$$anonfun$2.applyOrElse(AkkaHttpServer.scala:417)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:453)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

spray.json.DeserializationException: Object is missing required member 'access_token'
    at spray.json.package$.deserializationError(package.scala:23)
    at spray.json.ProductFormats.fromField(ProductFormats.scala:61)
    at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
    at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
    at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:81)
    at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:71)
    at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:31)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
    at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

java.util.NoSuchElementException: key not found: access_token
    at scala.collection.MapOps.default(Map.scala:246)
    at scala.collection.MapOps.default$(Map.scala:245)
    at scala.collection.AbstractMap.default(Map.scala:376)
    at scala.collection.MapOps.apply(Map.scala:148)
    at scala.collection.MapOps.apply$(Map.scala:147)
    at scala.collection.AbstractMap.apply(Map.scala:376)
    at spray.json.ProductFormats.fromField(ProductFormats.scala:58)
    at spray.json.ProductFormats.fromField$(ProductFormats.scala:51)
    at spray.json.DefaultJsonProtocol$.fromField(DefaultJsonProtocol.scala:30)
    at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:81)
    at spray.json.ProductFormatsInstances$$anon$3.read(ProductFormatsInstances.scala:71)
    at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:31)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
    at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
    at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:51)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:447)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:92)
    at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:92)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:47)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:47)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### PR DESCRIPTION
**Pull request by francisdb**
Fixes #2080

Some notes
* This adds 2s to the test time because the first backoff according to the google GCS SLA should be 1s
* I have not fully tested the negative case where a total 32 sec backoff is required
* Is this `RuntimeException` ok?

### CODE REVIEW

**Comment by francisdb** [comment]
Would be great if this could make it to `2.0.0-M3`

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleSession.scala [hunk 1]
```diff
@@ -5,7 +5,7 @@
 package akka.stream.alpakka.googlecloud.pubsub.impl
 
 import akka.annotation.InternalApi
-import akka.stream.Materializer
+import akka.stream.ActorMaterializer
```
Comment (ennru) [inline google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleSession.scala]: Why this `ActorMaterializer`?

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    // Exponential backoff as specified in the GCS SLA: https://cloud.google.com/storage/sla
+
+    // 1 initial attempt, plus 2^5 exponential requests to get to 32 seconds
+    val remainingAttempts = new AtomicInteger(6)
+    RestartSource
+      .withBackoff(
+        minBackoff = 1.second,
+        maxBackoff = 32.seconds,
+        randomFactor = 0
+      ) { () =>
```
Comment (ennru) [inline google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: I wonder if this could be solved more idiomatically with a `RetryFlow` (which would need be copied in for Akka 2.5 support).

Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: I did not write this part, just moved it over here for reuse.

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleSession.scala (hunk 1 above)
Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleSession.scala]: Removed where not needed

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala (hunk 2 above)
Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: anyway, looking into this

Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: Also synced both implementations, their files are almost identical

Comment (francisdb) [reply google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: @ennru better like this?

**Comment by francisdb** [comment]
both projects have the same tests but the storage one logs this during testing (test does not fail):

```
[ERROR] [02/14/2020 13:55:51.422] [default-akka.actor.default-dispatcher-5] [akka://default/system/StreamSupervisor-0/flow-2-0-headSink] Error during postStop in [akka.stream.alpakka.googlecloud.storage.impl.backport.RetryFlowCoordinator@7e6d0375]: null
java.lang.NullPointerException
	at akka.stream.stage.GraphStageLogic.afterPostStop(GraphStage.scala:1332)
	at akka.stream.stage.TimerGraphStageLogic.afterPostStop(GraphStage.scala:1608)
	at akka.stream.impl.fusing.GraphInterpreter.finalizeStage(GraphInterpreter.scala:580)
	at akka.stream.impl.fusing.GraphInterpreter.afterStageHasRun(GraphInterpreter.scala:560)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:424)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:606)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:485)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:581)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:749)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:764)
	at akka.actor.Actor.aroundReceive(Actor.scala:539)
	at akka.actor.Actor.aroundReceive$(Actor.scala:537)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:671)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:612)
  | => aat akka.actor.ActorCell.invoke(ActorCell.scala:581)okenApiSpec 2s
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:268)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:241)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by francisdb** [comment]
> Once we the solution is OK, we'd want to propagate it to Alpakka Google Cloud Storage.

This PR is for both?

**Comment by ennru** [comment]
The `RetryFlow` shines here ;-)
Why the switch to `ActorMaterializer`? It should be just `Materializer` if there is no special need.

**Comment by francisdb** [comment]
@ennru I removed all those `ActorMaterializer`s that I added before, were indeed not needed. The reason why `ActorMaterializer` is used in some places is because we need an `ActorSystem` to use `Http()`.

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala [hunk 3]
```diff
@@ -51,15 +51,30 @@ private[googlecloud] class GoogleTokenApi(http: => HttpExt) {
...
+  private def validateResponse(response: HttpResponse)(implicit mat: Materializer): Future[HttpResponse] = {
+    import mat.executionContext
+    response match {
+      case HttpResponse(StatusCodes.ServerError(status), _, responseEntity, _) =>
+        Unmarshal(responseEntity).to[String].map[HttpResponse] { body =>
+          throw new RuntimeException(s"Failed to request token, got $status with body: $body")
+        }
+      case other => Future.successful(other)
+    }
+  }
```
Comment (ennru) [inline google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleTokenApi.scala]: This could go into the flow in `GoogleRetry`.

File: google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+
+import scala.concurrent.Future
+import scala.concurrent.duration._
+
+@InternalApi
+private[googlecloud] object GoogleRetry {
+
+  // Exponential backoff as specified in the GCS SLA: https://cloud.google.com/storage/sla
+  // 1 initial attempt, plus 2^5 exponential requests to get to 32 seconds
+
```
Comment (ennru) [inline google-cloud-pub-sub/src/main/scala/akka/stream/alpakka/googlecloud/pubsub/impl/GoogleRetry.scala]: This could be API docs.

**Comment by ennru** [comment]
Thank you @francisdb, a great improvement!
