### PR TITLE
Fix Amqp pub-sub tests to not depend on broker timings

### LINKED ISSUE #20: AmqpConnectorsTest.publishFanoutAndConsume
```
[info] Test akka.stream.alpakka.amqp.AmqpConnectorsTest.publishFanoutAndConsume started
[error] Test akka.stream.alpakka.amqp.AmqpConnectorsTest.publishFanoutAndConsume failed: java.util.concurrent.TimeoutException: null, took 10.468 sec
[error]     at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1771)
[error]     at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.scala$concurrent$java8$FuturesConvertersImpl$CF$$super$get(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF$$anonfun$get$2.apply(FutureConvertersImpl.scala:84)
[error]     at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error]     at scala.concurrent.package$.blocking(package.scala:123)
[error]     at scala.concurrent.java8.FuturesConvertersImpl$CF.get(FutureConvertersImpl.scala:84)
[error]     at akka.stream.alpakka.amqp.AmqpConnectorsTest.publishFanoutAndConsume(AmqpConnectorsTest.java:141)
[error]     ...
[info] Test run finished: 1 failed, 0 ignored, 2 total, 10.785s
```

https://travis-ci.org/akka/alpakka/builds/173177910

### PR DESCRIPTION
**Pull request by 2m**
Fixes #20

### CODE REVIEW

File: amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java [hunk 1]
```diff
@@ -118,28 +117,24 @@ public void publishFanoutAndConsume() throws Exception {
...
+      system.dispatcher());
 
-     final Set<Pair<Integer, String>> expectedResult = input
-       .stream()
-       .flatMap(str -> IntStream.range(0, fanoutSize).boxed().map(i -> Pair.create(i, str)))
-       .collect(Collectors.toSet());
+     Source.repeat("stuff").map(ByteString::fromString).runWith(amqpSink, materializer);
 
-     assertEquals(expectedResult, result.toCompletableFuture().get(10, TimeUnit.SECONDS).stream().collect(Collectors.toSet()));
+     assertEquals(Done.getInstance(), completion.toCompletableFuture().get(10, TimeUnit.SECONDS));
```
Comment (patriknw) [inline amqp/src/test/java/akka/stream/alpakka/amqp/javadsl/AmqpConnectorsTest.java]: isn't it already a `CompletableFuture`?
