### PR TITLE
SQS: Revise stream element data model

### LINKED ISSUE #625: No support for SQS Fifo queue?
When I try to use a FIFO queue, I get the following error:

> The request must contain the parameter MessageGroupId. (Service: AmazonSQS; Status Code: 400; Error Code: MissingParameter; Request ID: 628341eb-8a17-5841-a110-1374cae6b8a1)

If I simply change the `sqsEndpoint` to a non-fifo SQS queue, everything works as expected. I don't see how to even pass the message group ID, so it looks like it is unsupported at the moment, is this correct?

### PR DESCRIPTION
**Pull request by RustedBones**
# Pull Request Checklist

* [x] Have you read through the [contributor guidelines](https://github.com/akka/alpakka/tree/master/CONTRIBUTING.md) and [contributor advice](https://github.com/akka/alpakka/blob/master/contributor-advice.md)?
* [x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [x] Have you updated the documentation?
* [x] Have you added tests for any changed functionality?

## Fixes

Fixes #625

## Purpose

Improve SQS batch operations

## Background Context

After the AWS SDK update, changes in the AWS models can make the API simpler and cleaner:
- No need to propagate FifoIdentifiers anymore
- Separation between request metadata (HTTP request info) and content metadata

### CODE REVIEW

**Comment by ennru** [comment]
Thank you for modernising this with the latest possibilities from the AWS SDK.
As we now want to promise binary compatibility between releases, this PR failed the MiMa check. Do you see a way to keep the RC1 API around while improving this?

(run `mimaReportBinaryIssues` to get the MiMa report locally)

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala [hunk 1]
```diff
@@ -125,70 +126,50 @@ object MessageAction {
 }
 
 /**
- * Additional identifiers for FIFO messsages
+ * Messages returned by a SqsFlow.
  *
- * @see [https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-additional-fifo-queue-identifiers.html]
+ * @param message the SQS message.
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: Please fix left-over to describe what we have now.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala [hunk 2]
```diff
@@ -107,40 +95,24 @@ object SqsPublishFlow {
         sqsClient
           .sendMessageBatch(req)
           .toScala
-          .map(req -> _)(sameThreadExecutionContext)
       }
-      .mapAsync(settings.concurrentRequests) {
-        case (request, response) if !response.failed().isEmpty =>
+      .map {
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsPublishFlow.scala]: Great to remove the unused Future-wrapping.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala [hunk 3]
```diff
@@ -30,7 +31,7 @@ object SqsAckFlow {
    */
   def apply(queueUrl: String, settings: SqsAckSettings = SqsAckSettings.Defaults)(
       implicit sqsClient: SqsAsyncClient
-  ): Flow[MessageAction, SqsAckResult[SqsResponse], NotUsed] =
+  ): Flow[MessageAction, SqsAckResult[SdkPojo], NotUsed] =
```
[the remark this answers is not in the document]
Comment (RustedBones) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala]: This improves the consistency for Batch actions.
In this case we want to give the metadata entry associated to the single `MessageAction` and not the response which was sent back from the whole batch.

As mentioned in #625, in the batch `SqsResponse`, we don't have any way to identify the specific metadata entry for the `MessageAction` because we don't know the batch id. (we may be able to do it by comparing md5 hashes of the messages but that's not nice)

[the remark this answers is not in the document]
Comment (ennru) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/scaladsl/SqsAckFlow.scala]: But here we don't have batches. We can use `SdkPojo` for the batch actions.

**Comment by ennru** [comment]
This PR requires a rebase to incorporate changes from #1606.

**Comment by RustedBones** [comment]
Thanks @ennru. 
By going through the PR once more, I realize I may got rid of the `FifoMessageIdentifiers` a bit too early. The goal of this class was to propagate the `GroupId` and `DeduplicationId` to downstream in case the user wants to do some special operations depending on those values (like for the message, we propagate it downstream though SQS only gives the md5 as a response).

In order to pass all information to downstream, we can encapsulate the `SendMessageRequest` into the `SqsPublishResult`. Then we can safely remove the `FifoMessageIdentifiers` and this makes it more symmetric like the `SqsAckFlow` which also contains the `MessageAction`.

**Comment by ennru** [comment]
Let's give this the time it needs and release Alpakka 1.0 anyway. I've created #1621 to mark the API as "may change".

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala [hunk 4]
```diff
@@ -125,82 +126,78 @@ object MessageAction {
...
+    s"""SqsPublishResult(responseMetadata=$responseMetadata,metadata=$metadata,request=$request)"""
 
   override def equals(other: Any): Boolean = other match {
-    case that: FifoMessageIdentifiers =>
-      java.util.Objects.equals(this.sequenceNumber, that.sequenceNumber) &&
-      java.util.Objects.equals(this.messageGroupId, that.messageGroupId) &&
-      java.util.Objects.equals(this.messageDeduplicationId, that.messageDeduplicationId)
+    case that: SqsPublishResult[T] =>
+      java.util.Objects.equals(this.responseMetadata, that.responseMetadata) &&
+      java.util.Objects.equals(this.metadata, that.metadata)
```
[the remark this answers is not in the document]
Comment (RustedBones) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: Good catch. Should have triggered an error in the test but I made an error there.

I'm still wondering why in `alpakka` we didn't go the `akka-http` way for the model: Java abstract classes/interface with the java api in a `javadsl` package and scala case classes in `scaladsl` extending the java api. We'll then not have to case of the `toString` and `equal`. Is it because of `copy` ?

[the remark this answers is not in the document]
Comment (ennru) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: Yes. Copy's generated default parameters make it hard to evolve case classes in a binary-compatible way.

**Comment by ennru** [comment]
Picking this up again.

To reduce the risk for "`ToManyTypeParametersException`" I'd like to propose to introduce specific subclasses of `SqsPublishResult`:

```scala
final class SqsPublishSingleResult @InternalApi private[sqs] (
    responseMetadata: SqsResponseMetadata,
    metadata: SendMessageResponse,
    request: SendMessageRequest
) extends SqsPublishResult[SendMessageResponse](responseMetadata, metadata, request)

final class SqsPublishBatchResult @InternalApi private[sqs] (
    responseMetadata: SqsResponseMetadata,
    metadata: SendMessageBatchResultEntry,
    request: SendMessageRequest
) extends SqsPublishResult[SendMessageBatchResultEntry](responseMetadata, metadata, request)
```

Names can be improved probably, but the API looks simpler with this.

WDYT?

**Comment by RustedBones** [comment]
Are we risking a `ToManyTypeParametersException` since the constructor visibility is package?

If we do this we should also do the same with `SqsAckResult` with `ChangeMessageVisibilityResponse`, `ChangeMessageVisibilityBatchResultEntry`,  `DeleteMessageResponse`, `DeleteMessageBatchResultEntry` and `SqsAckResult[Nothing]` (returned in a case of `MessageAction.Ignore`). That make all the type definitions a bit tedious IMHO.

**Comment by ennru** [comment]
Yes, you're right.

**Comment by RustedBones** [comment]
Thinking about it again, it's probably better to give a sealed abstract class along with the possible implementations for the SQS model

Right now, the output type from the `SqsAckFlow.grouped` is a `SqsAckResult[SdkPojo]` which is contains too many potential implementations due to the `SdkPojo` (not only used for SQS)  and would oblige the users to always provide a default case when pattern matching to be exhaustive. Same problem applies with `SqsResponse` in a smaller scale.

In addition, it would also be nice to provide unapply on the SQS model  for the scala users

**Comment by ennru** [comment]
Yes, that is what I am looking for. `SdkPojo` is too broad and we have just two specialisations of it.

**Comment by RustedBones** [comment]
I've tried to get rid of the type parameter from the publish and ack results to give a clean API:
```scala
SqsPublishFlow.apply: Flow[SendMessageRequest, PublishResult, NotUsed]
SqsPublishFlow.grouped: Flow[SendMessageRequest, PublishResultEntry, NotUsed]

SqsAckFlow.apply: Flow[MessageAction, SqsAckResult, NotUsed]
SqsAckFlow.grouped: Flow[MessageAction, SqsAckResultEntry, NotUsed]
``` 

`Ignore` message action is now filtered by the ack flows and don't forward any message downstream

In all the `SqsResult` there is an accessor to the `SqsResponseMetadata` but this field is not taken in account for the `equals` and `toString` as AWS does it on its own models.

File: sqs/src/test/java/docs/javadsl/SqsAckTest.java [hunk 5]
```diff
@@ -92,27 +96,31 @@ public void testAcknowledge() throws Exception {
...
     SqsAsyncClient awsClient = mock(SqsAsyncClient.class);
     when(awsClient.deleteMessage(any(DeleteMessageRequest.class)))
-        .thenReturn(CompletableFuture.completedFuture(DeleteMessageResponse.builder().build()));
+        .thenReturn(CompletableFuture.completedFuture(response));
 
-    List<Message> messages = createMessages();
     Source<Message, NotUsed> source = Source.fromIterator(messages::iterator);
-
-    CompletionStage<List<SqsAckResult<SqsResponse>>> stage =
+    CompletionStage<List<SqsAckResult>> stage =
```
Comment (ennru) [inline sqs/src/test/java/docs/javadsl/SqsAckTest.java]: Nice.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala [hunk 6]
```diff
@@ -125,89 +124,213 @@ object MessageAction {
...
 
   /** Java API */
-  def getMessageDeduplicationId: java.util.Optional[String] = messageDeduplicationId.asJava
+  def getResult: Result = result
+}
+
+/**
+ * Messages returned by a SqsPublishFlow
+ */
+final class PublishResult @InternalApi private[sqs] (
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: No `Sqs` prefix? Was that intentional?

Comment (RustedBones) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: The `MessageActions` are not prefixed with `Sqs`.

But you're right, I'm inconsistent with the naming: the super class are prefixed but not the implementations. I should either remove or prepend it everywhere.

**Comment by RustedBones** [comment]
I've added `Ignore` to the `SqsAck`.
Instead of using `Option` for the `result` and `requestMetadata`, I return `NotUsed` and an empty metadata object.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala [hunk 7]
```diff
@@ -35,14 +36,14 @@ object MessageAction {
   }
 
   final object Delete {
-    def apply(message: Message): MessageAction = new Delete(message)
+    def apply(message: Message): Delete = new Delete(message)
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: I'm looking into the MiMa differences and this change shows up. It should stay as `MessageAction` which makes the generics a bit easier for Java users.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala [hunk 8]
```diff
@@ -53,7 +54,7 @@ object MessageAction {
   }
 
   final object Ignore {
-    def apply(message: Message): MessageAction = new Ignore(message)
+    def apply(message: Message): Ignore = new Ignore(message)
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: Same as for `Delete`, keep `MessageAction`.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala [hunk 9]
```diff
@@ -3,53 +3,46 @@
...
+                              responseMetadata: SqsResponseMetadata = EmptySqsResponseMetadata): SqsDeleteResultEntry =
+    new SqsDeleteResultEntry(messageAction, result, responseMetadata)
+
+  def createChangeMessageVisibilityResultEntry(
+      messageAction: MessageAction.ChangeMessageVisibility,
+      result: ChangeMessageVisibilityBatchResultEntry,
+      responseMetadata: SqsResponseMetadata = EmptySqsResponseMetadata
+  ): SqsChangeMessageVisibilityResultEntry =
+    new SqsChangeMessageVisibilityResultEntry(messageAction, result, responseMetadata)
 }
```
Comment (ennru) [inline sqs/src/main/scala/akka/stream/alpakka/sqs/testkit/MessageFactory.scala]: Please add `SqsIgnoreResult` and `SqsIgnoreResultEntry` factories here.

File: sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala (hunk 7 above)
Comment (RustedBones) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: The Java users should use `MessageAction.delete(message: Message): MessageAction` instead `apply`.

Comment (ennru) [reply sqs/src/main/scala/akka/stream/alpakka/sqs/SqsModel.scala]: Of course. Thank you.
