### PR TITLE
Fix #343 by handling preStart failures explicitly

### LINKED ISSUE #343: AMQP: Sink promise never completes if connection fails
If opening a connection to rabbit during stage preStart fails, the AmpqSinkStage's promise will never be completed.

### PR DESCRIPTION
**Pull request by Falmarri**
If an error happened in preStart, the future wouldn't be completed and anyone mapping on the result would just hang on that future.

### CODE REVIEW

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala [hunk 1]
```diff
@@ -91,6 +91,15 @@ final class AmqpSinkStage(settings: AmqpSinkSettings)
...
         }
       )
+
+      override def postStop(): Unit = {
+        promise.tryFailure(new RuntimeException("stage stopped unexpectedly"))
+        super.postStop()
+      }
+
+      override def onFailure(ex: Throwable): Unit =
+        promise.tryFailure(ex)
```
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala]: `super.onFailure` call too?

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala [hunk 2]
```diff
@@ -148,6 +157,9 @@ final class AmqpReplyToSinkStage(settings: AmqpReplyToSinkSettings)
         super.postStop()
       }
 
+      override def onFailure(ex: Throwable): Unit =
+        promise.tryFailure(ex)
```
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala]: super call?

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala [hunk 3]
```diff
@@ -129,7 +129,7 @@ final class AmqpSourceStage(settings: AmqpSourceSettings, bufferSize: Int)
           false // just this single message
         )
       }
-
+      override def onFailure(ex: Throwable): Unit = {}
```
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala]: are you sure?

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala (hunk 1 above)
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala]: Meh, nevermind I see that's your custom method and not the GraphStageLogic one

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala (hunk 2 above)
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala]: Meh, nevermind I see that's your custom method and not the GraphStageLogic one

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala (hunk 3 above)
Comment (ktoso) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSourceStage.scala]: Meh, nevermind I see that's your custom method and not the GraphStageLogic one

File: amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala (hunk 1 above)
Comment (Falmarri) [inline amqp/src/main/scala/akka/stream/alpakka/amqp/AmqpSinkStage.scala]: Should i rename the method since it apparently is somewhat confusing?

**Comment by Falmarri** [comment]
@ktoso ping =]
