### PR TITLE
Kinesis: towards 1.0

### LINKED ISSUE #1481: Kinesis: Iterator Type At Timestamp needs timestamp set first
### Versions used 
Alpakka version: ____ 1.0-M2
Akka version: ____ 2.5.19
Scala Library____ 2.12.7
Aws Java Sdk Kinesis____ 1.11.476
Java JRE____ both 1.8 and 10

below is my config code of gradle
```gradle
// Apply the java-library plugin to add support for Java Library
apply plugin: 'java-library'

targetCompatibility = '10'

// In this section you declare where to find the dependencies of your project
repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
}

dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'com.google.guava:guava:23.0'

	compile group: 'com.amazonaws', name: 'aws-java-sdk-kinesis', version: '1.11.476'
	compile group: 'org.scala-lang', name: 'scala-library', version: '2.12.7'
	compile group: 'com.typesafe.akka', name: 'akka-stream_2.12', version: '2.5.19'
	compile group: 'com.lightbend.akka', name: 'akka-stream-alpakka-kinesis_2.12', version: '1.0-M2'
	
    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
}
```

### Expected Behavior

I'm choosing framework to collaborate within AWS kinesis.
So I wrote an JAVA program to test it.
It work so fine with `ShardIteratorType.LATEST` and `ShardIteratorType.TRIM_HORIZON`
but not working within ShardIteratorType.AT_TIMESTAMP and other!

below is my code
```JAVA
    // config client
    AmazonKinesisAsyncClientBuilder clientBuilder = AmazonKinesisAsyncClientBuilder.standard();
    clientBuilder.setRegion("ap-northeast-1");
    clientBuilder.setCredentials(credentialsProvider);
    clientBuilder.setClientConfiguration(config);

    final AmazonKinesisAsync amazonKinesisAsync = clientBuilder.build();
    system.registerOnTermination(amazonKinesisAsync::shutdown);

    // get shard info
    DescribeStreamRequest describeStreamRequest = new DescribeStreamRequest();
    describeStreamRequest.setStreamName(STREAM_NAME);
    DescribeStreamResult describeStreamResult = amazonKinesisAsync.describeStream(describeStreamRequest);
    List<Shard> shards = describeStreamResult.getStreamDescription().getShards();

    ArrayList<ShardSettings> mergeSettings = new ArrayList<ShardSettings>();

    for (Shard shard : shards) {
      System.out.println(shard.getShardId());

      if (shard.getSequenceNumberRange().getEndingSequenceNumber() == null) {
        System.out.println(shard.getShardId());

        Date atTimestamp = new Date(new SimpleDateFormat("yyyy/MM/dd hh:mm").parse("2019/02/06 10:00").getTime());

        mergeSettings.add(
            ShardSettings.create(STREAM_NAME, shard.getShardId()).withShardIteratorType(ShardIteratorType.AT_TIMESTAMP)
                .withAtTimestamp(atTimestamp).withRefreshInterval(1, TimeUnit.SECONDS).withLimit(500));

        System.out.println(shard.getShardId() + " is OPEN.");
      } else {
        System.out.println(shard.getShardId() + " is CLOSED.");
      }
    }

    final Source<Record, NotUsed> source = KinesisSource.basicMerge(mergeSettings, amazonKinesisAsync);

    Sink<Record, CompletionStage<Done>> sink = Sink.foreach(record -> {
      System.out.print(record.toString());
      System.out.print("Data:");
      System.out.println(StandardCharsets.UTF_8.decode(record.getData()).toString());
    });

    source.async().to(sink).run(materializer);
```

### Actual Behavior

When I run my program within ShardIteratorType.AT_TIMESTAMP. The following Error was happened.
```error
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed
	at scala.Predef$.require(Predef.scala:268)
	at akka.stream.alpakka.kinesis.ShardSettings.<init>(ShardSettings.scala:76)
	at akka.stream.alpakka.kinesis.ShardSettings.copy(ShardSettings.scala:68)
	at akka.stream.alpakka.kinesis.ShardSettings.withShardIteratorType(ShardSettings.scala:81)
	at com.example.kinesis.reader.Reader.main(Reader.java:73)
```

I find and view your Example code, It was pretty for Scala, but for Java example you didn't write any example for other ShardIteratorType excepted ShardIteratorType.LATEST.
[https://github.com/akka/alpakka/blob/master/kinesis/src/test/java/akka/stream/alpakka/kinesis/javadsl/Examples.java](url)

Please check and Reply! Thankyou!

### PR DESCRIPTION
**Pull request by ennru**
## Fixes

Fixes #1481, #1080

## Purpose

It makes the Kinesis connector follow Alpakka's recommended code structure:
* internals in the `impl` package
* snippet code sourced from `docs.scaladsl` and `docs.javadsl`
* settings aren't case classes

I tried to simplify the graph stages quite a bit.

### CODE REVIEW

File: kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala [hunk 1]
```diff
@@ -4,93 +4,121 @@
...
+   * Sets `shardIteratorType` to `AFTER_SEQUENCE_NUMBER` and uses the given value as starting sequence number.
    */
-  def create(streamName: String,
-             shardId: String,
-             shardIteratorType: ShardIteratorType,
-             refreshInterval: FiniteDuration,
-             limit: Integer) =
-    ShardSettings(streamName, shardId, shardIteratorType, None, None, refreshInterval, limit)
+  def withStartingAfterSequenceNumber(value: String): ShardSettings =
+    copy(shardIteratorType = ShardIteratorType.AFTER_SEQUENCE_NUMBER, startingSequenceNumber = Option(value))
```
Comment (2m) [inline kinesis/src/main/scala/akka/stream/alpakka/kinesis/ShardSettings.scala]: These are really useful when the type and some property needs to be set in coordination.
